const IMAGE_MESSAGE_TYPE = 'IMAGE_MESSAGE_TYPE';
const TEXT_MESSAGE_TYPE = 'TEXT_MESSAGE_TYPE';
const STICKER_MESSAGE_TYPE = 'STICKER_MESSAGE_TYPE';
const JOIN_ROOM_MESSAGE_TYPE = 'JOIN_ROOM_MESSAGE_TYPE';
